site_name: ERCOT Developer Site
theme:
  name: material
  logo: icons/MicrosoftTeams-image.png
  palette:
  - scheme: default
    primary: white
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

plugins:
  - render_swagger

nav:
  - Home: index.md
  - Technical Reference:
    - techref/Guidelines.md
  - OpenAPI Specifications:
    - openapi/petstore.md
  - EWS Specifications:
    - EWS/ews.md
  - ISO URLs:
    - mis and ercot.com/details.md
  - Release Planning:
    - mis and ercot.com/details.md
  - Browser Support:
    - mis and ercot.com/details.md
   


  


