site_name: ERCOT Developer Site
theme:
  name: material
  logo: icons/MicrosoftTeams-image.png
  palette:
  - scheme: default
    primary: white
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  
 markdown_extensions:
  - attr_list


plugins:
  - render_swagger

nav:
  - Home: index.md
  - API Details:
    - EWS/ews.md
    - EWS/API Terms of Use.md
  - Sites:
    - mis and ercot.com/details.md
  - Release Planning:
    - Release Planning/releaseplanning.md
  - Browser Support:
    - Brower Support/browsersupport.md
  - Apps:
    - Apps/Apps.md
  - FAQs:
    - FAQ/faq.md
  - Identity and Access Management:
    - IAM/iam.md
  - Technical Reference:
    - techref/Guidelines.md
  - OpenAPI Specifications:
    - openapi/petstore.md

  


